version: "3"

services:
  app:
    build:
      context: ./server
      dockerfile: ./dev.dockerfile
      tags:
        - "gustrody:dev"
    env_file:
      - ".env"
    environment:
      POSTGRES_HOST: db:5432
      POSTGRES_SECRET_FILE: /run/secrets/postgres_secret
      CACHE_HOST: cache:6739
      REDIS_SECRET_FILE: /run/secrets/redis_secret
    ports:
      - "${PORT}:8000"
    networks:
      - gustrody
    volumes:
      - ./server:/app
    secrets:
      - postgres_secret
      - redis_secret
    depends_on:
      - db
      - cache
    restart: unless-stopped

  db:
    image: postgres:16.1-alpine
    env_file:
      - ".env"
    environment:
      POSTGRES_DB: austrody
      POSTGRES_PASSWORD_FILE: /run/secrets/postgres_secret
    ports:
      - 5432:5432
    networks:
      - gustrody
    secrets:
      - postgres_secret
    volumes:
      - austrody_main_dev:/var/lib/postgresql/data
      - ./db/main_init.sql:/docker-entrypoint-initdb.d/init_db.sql
    restart: unless-stopped
  
  cache:
    image: redis:7.2.4-alpine
    environment:
      SECRET_FILE: "/run/secrets/redis_secret"
      CONFIG_FILE: "/usr/local/etc/redis-cache.conf"
    ports:
      - 6738:6739
    networks:
      - gustrody
    volumes:
      - ./db/redis_startup.sh:/startup.sh
      - ./db/redis_cache.conf:/redis.conf
    secrets:
      - redis_secret
    restart: unless-stopped
    entrypoint: /startup.sh

volumes:
  # default style: managed by docker
  # optional style: specify a path as volume
  austrody_main_dev:
    external: true

secrets:
  postgres_secret:
    file: ./db/postgres_password
  redis_secret:
    file: ./db/redis_password

networks:
  gustrody: