port 6739
requirepass {REDIS_SECRET}

loglevel warning
logfile "/data/persist.log"

# db 0: for some persist key-value pairs
databases 1

save 300 1 60 2
dir /data
dbfilename persist.db
rdbchecksum yes